### ISSUE TITLE
We forgot to make a new release with the old color scheme and component types

### ISSUE THREAD

**Issue by onodip** [mdolab/pyXDSM#15]
Release 1.0 is more than a year old, and it is missing some of the new options and bugfixes, which would be applicable regardless of the recent changes. Would it be possible to make a 1.0.1 version for the people, who want to use the old style (just before #11)?

**Comment by nwu63** [comment]
I believe the colors were changed from v1.0 with commit 2545897dbe57a4fa2c8c1c68ae09bb578169298a, well before PR #11. So if we want, we can tag the commit just before that, but it won't have the changes between that and the PR.

**Comment by onodip** [comment]
> I believe the colors were changed from v1.0 with commit [2545897](https://github.com/mdolab/pyXDSM/commit/2545897dbe57a4fa2c8c1c68ae09bb578169298a), well before PR #11. So if we want, we can tag the commit just before that, but it won't have the changes between that and the PR.

True, the colors changed for the first time a long while ago. I think this way it is not worth to make a new tag.
