### ISSUE TITLE
Better handling of pdflatex compilation failure

### ISSUE THREAD

**Issue by jgiret** [mdolab/pyXDSM#36]
# Description of feature
Currently, the call to pdflatex is done by using a os.system call. However, this is not recommended (https://docs.python.org/3/library/subprocess.html#replacing-os-system), and in this case it is not possible to retrieve the return code at the end of the execution. It would allow to raise an exception when an error is encountered during the compilation of the .tex file. We have experienced silent errors of the .tex compilation (either because the latex distribution was not recent enough, or because special characters were not escaped), and we are currently checking the existence of the pdf output file at the end, which is not optimal. 

# Potential solution
I would replace the os.system call by a subprocess.call, and raise an exception if the return code is different from 0. I think this is a very small and easy development, and I can submit you a PR if you wish. Tell me what is the best option for you.

**Comment by JustinSGray** [comment]
though Im not currently the lead maintainer of this repo, I would personally approve of a PR for this. It sounds like a good change.

**Comment by eirikurj** [comment]
@jgiret I encourage you to submit a PR for this.
