### ISSUE TITLE
How to create line breaks in text boxes?

### ISSUE THREAD

**Issue by michK** [mdolab/pyXDSM#41]
Hi,

I'm trying to create text in input/output/connection boxes that span multiple lines, but it doesn't look like the latex `//` or `\newline` commands are respected.

I don't see this being done in any of the examples, but I do see it in Mr Gray's pyCycle paper, so figure it must be possible.

Thanks in advance
Michael

**Comment by michK** [comment]
Nevermid I see this is covered in the API doc page.

**Comment by nwu63** [comment]
Line breaks are achieved by passing in a list of strings to the `label` argument. See [this docstring](https://mdolab-pyxdsm.readthedocs-hosted.com/API.html#pyxdsm.XDSM.XDSM.add_input) for example, but the same applies to all applicable `add_` function calls.
